apiVersion: v1
kind: Service
metadata:
  name: opensearch-svc
  namespace: order-service-ns
spec:
  ports:
  - name: http
    port: 9200
    targetPort: 9200
  selector:
    app: opensearch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch-node
  namespace: order-service-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      containers:
      - name: opensearch
        image: opensearchproject/opensearch:2.14.0
        env:
        - name: discovery.type
          value: "single-node"
        - name: DISABLE_SECURITY_PLUGIN
          value: "true"
        - name: OPENSEARCH_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        ports:
        - containerPort: 9200
          name: http
