apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: order-service-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo
          image: grafana/tempo:2.10.0
          args:
            - "-config.file=/etc/tempo/tempo.yaml"
          ports:
            - name: http
              containerPort: 3200
            - name: otlp-grpc
              containerPort: 4317
            - name: otlp-http
              containerPort: 4318
          volumeMounts:
            - name: tempo-config
              mountPath: /etc/tempo
            - name: tempo-storage
              mountPath: /tmp/tempo
      volumes:
        - name: tempo-config
          configMap:
            name: tempo-config
        - name: tempo-storage
          emptyDir: {}

